FROM python:3.9-bullseye

ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_DEFAULT_REGION
ARG AWS_BUCKET_NAME

ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
ENV AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
ENV AWS_BUCKET_NAME=$AWS_BUCKET_NAME

RUN apt-get update && \
    apt-get install -y git nano unzip && \
    curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip" && \
    unzip awscli-bundle.zip && \
    ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws && \
    rm -rf awscli-bundle awscli-bundle.zip

RUN python -m pip install --upgrade pip

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait

WORKDIR /deps
COPY requirements.txt requirements.txt
RUN python -m pip install -r requirements.txt

WORKDIR /app
COPY aws-config.sh /app/aws-config.sh
RUN chmod +x /app/aws-config.sh

CMD /wait && python -m migrations up && uvicorn main:app --reload --host 0.0.0.0

